Repository MATEBALL/MATEBALL-SERVER, pull requests merged in 2025-07, with the labels that each got.

#26 [chore/#25] 패키지 네이밍 수정
  src/main/java/at/mateball/domain/gameinformation/core/GameInformation.java
  src/main/java/at/mateball/domain/group/core/Group.java
  src/main/java/at/mateball/domain/groupmember/core/GroupMember.java
  src/main/java/at/mateball/domain/matchrequirement/core/MatchRequirement.java
  src/main/java/at/mateball/domain/user/core/User.java
Labels: (˵ᵕ̴᷄ ˶̫ ˶ᵕ̴᷅˵) 혜으미 (˵ᵕ̴᷄ ˶̫ ˶ᵕ̴᷅˵), fix

#31 [feat/#30] 코드래빗 yaml 파일 추가
  .coderabbit.yaml
Labels: (˵ᵕ̴᷄ ˶̫ ˶ᵕ̴᷅˵) 혜으미 (˵ᵕ̴᷄ ˶̫ ˶ᵕ̴᷅˵), yml

#85 [feat/#76] 그룹 멤버 상태 변환
  src/main/java/at/mateball/domain/groupmember/api/controller/GroupMemberController.java
  src/main/java/at/mateball/domain/groupmember/core/repository/querydsl/GroupMemberRepositoryCustom.java
  src/main/java/at/mateball/domain/groupmember/core/repository/querydsl/GroupMemberRepositoryImpl.java
  src/main/java/at/mateball/domain/groupmember/core/service/GroupMemberService.java
Labels: ⎛⎝O⏝⏝O⎛⎝ 다지니 ⎛⎝O⏝⏝O⎛⎝, feat

#108 [fix] NPE 처리
  src/main/java/at/mateball/domain/group/core/repository/querydsl/GroupRepositoryImpl.java
  src/main/java/at/mateball/domain/group/core/service/GroupService.java
Labels: ⎛⎝O⏝⏝O⎛⎝ 다지니 ⎛⎝O⏝⏝O⎛⎝, feat

#114 [fix] 플로우 수정
  src/main/java/at/mateball/domain/groupmember/core/repository/querydsl/GroupMemberRepositoryImpl.java
  src/main/java/at/mateball/domain/groupmember/core/service/GroupMemberService.java
Labels: ⎛⎝O⏝⏝O⎛⎝ 다지니 ⎛⎝O⏝⏝O⎛⎝, fix

#124 [feat] 매칭 생성 및 요청 에러 코드 변경
  src/main/java/at/mateball/exception/code/BusinessErrorCode.java
Labels: (˵ᵕ̴᷄ ˶̫ ˶ᵕ̴᷅˵) 혜으미 (˵ᵕ̴᷄ ˶̫ ˶ᵕ̴᷅˵), feat

#126 [fix/#125] 예외 순서 및 추가
  src/main/java/at/mateball/domain/group/core/service/GroupService.java
Labels: ⎛⎝O⏝⏝O⎛⎝ 다지니 ⎛⎝O⏝⏝O⎛⎝, fix

#130 [chore/#128] DTO 경기장 정보 추가
  src/main/java/at/mateball/domain/groupmember/api/dto/DirectStatusRes.java
Labels: ⎛⎝O⏝⏝O⎛⎝ 다지니 ⎛⎝O⏝⏝O⎛⎝

#135 [refactor/#134] 그룹 매칭 리스트 수정
  src/main/java/at/mateball/domain/group/core/repository/querydsl/GroupRepositoryImpl.java
  src/main/java/at/mateball/domain/group/core/service/GroupService.java
Labels: ⎛⎝O⏝⏝O⎛⎝ 다지니 ⎛⎝O⏝⏝O⎛⎝, refactor

#137 [refactor] 매칭 현황 페이지
  src/main/java/at/mateball/domain/groupmember/core/repository/querydsl/GroupMemberRepositoryImpl.java
Labels: ⎛⎝O⏝⏝O⎛⎝ 다지니 ⎛⎝O⏝⏝O⎛⎝, refactor

#139 [feat/#138] 정렬 및 닉네임
  src/main/java/at/mateball/domain/groupmember/api/dto/DetailMatchingListRes.java
  src/main/java/at/mateball/domain/groupmember/core/repository/querydsl/GroupMemberRepositoryImpl.java
  src/main/java/at/mateball/domain/groupmember/core/service/GroupMemberService.java
  src/main/java/at/mateball/domain/user/core/repository/UserRepository.java
Labels: ⎛⎝O⏝⏝O⎛⎝ 다지니 ⎛⎝O⏝⏝O⎛⎝, feat

#141 [fix] 개수 검증 로직 순서 변경
  src/main/java/at/mateball/domain/group/core/service/GroupService.java
Labels: (˵ᵕ̴᷄ ˶̫ ˶ᵕ̴᷅˵) 혜으미 (˵ᵕ̴᷄ ˶̫ ˶ᵕ̴᷅˵), fix
