Repository MATEBALL/MATEBALL-SERVER, pull requests merged in 2025-08, with the labels that each got.

#162 [feat] 토큰 재발급
  src/main/java/at/mateball/domain/auth/api/controller/OAuthController.java
  src/main/java/at/mateball/domain/auth/core/service/ReissueService.java
Labels: ⎛⎝O⏝⏝O⎛⎝ 다지니 ⎛⎝O⏝⏝O⎛⎝, feat

#169 [feat] 닉네임 중복 조회 api 구현
  src/main/java/at/mateball/domain/user/api/controller/UserV2Controller.java
  src/main/java/at/mateball/domain/user/core/service/UserV2Service.java
Labels: (˵ᵕ̴᷄ ˶̫ ˶ᵕ̴᷅˵) 혜으미 (˵ᵕ̴᷄ ˶̫ ˶ᵕ̴᷅˵), feat

#171 [fix] "같은 팀 메이트" 를 입력하면 기존 enum 값과 매칭되도록 로직 추가
  src/main/java/at/mateball/domain/matchrequirement/core/constant/TeamAllowed.java
Labels: (˵ᵕ̴᷄ ˶̫ ˶ᵕ̴᷅˵) 혜으미 (˵ᵕ̴᷄ ˶̫ ˶ᵕ̴᷅˵), fix
